### ISSUE TITLE
Host Crashed Down

### ISSUE THREAD

**Issue by Diakkoo** [Diakkoo/docker-hadoop-container#1]
**It seems like adding Port-Mapping in MySQL container will crash down, when enter Hive server CLI**
```
mysql:
    image: "mysql:5.7.37"
    container_name: "mysql"
    hostname: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "hive"
    ports:
      - "3306:3306"
    networks:
      hnet:
        ipv4_address: "172.20.1.5"
    extra_hosts:
      - "nn:172.20.1.10"
      - "dn1:172.20.1.11"
      - "dn2:172.20.1.12"
      - "flask:172.20.1.4"
```
